//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        public string ID_ARTICULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_PRECIO { get; set; }
        public string IMG { get; set; }
    
        public virtual PRECIO PRECIO { get; set; }
    }
}
