//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVO
    {
        public int ID_CONSECUTIVOS { get; set; }
        public string NOMBRE { get; set; }
        public int VALOR { get; set; }
        public bool TIENE_PREFIJO { get; set; }
        public string PREFIJO { get; set; }
        public bool POSEE_RANGO { get; set; }
        public Nullable<int> RANGO_INICIAL { get; set; }
        public Nullable<int> RANGO_FINAL { get; set; }
    }
}
