//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACION()
        {
            this.CLIENTEs = new HashSet<CLIENTE>();
        }


        [DisplayName("ID")]
        public string ID_HABITACION { get; set; }
        [DisplayName("Numero")]
        public int NUMERO { get; set; }
        [DisplayName("Nombre")]
        public string NOMBRE { get; set; }
        [DisplayName("Descripcion")]
        public string DESCRIPCION { get; set; }
        [DisplayName("Foto")]
        public string FOTO { get; set; }
        [DisplayName("Tipo Habitacion")]
        public int TIPO_HABITACION { get; set; }
        [DisplayName("Precio")]
        public string ID_PRECIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTEs { get; set; }
        public virtual PRECIO PRECIO { get; set; }
        public virtual TIPO_HABITACION TIPO_HABITACION1 { get; set; }
    }
}
