//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public string ID_CONSECUTIVOS { get; set; }
        public string ID_USUARIO { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public string TIPO_HABITACION { get; set; }
        public int ESTADO_RESERVACION { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
