//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public string ID_RESERVACION { get; set; }
        public int ID_CLIENTE { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public int TIPO_HABITACION { get; set; }
        public int ESTADO_RESERVACION { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_RESERVACION ESTADO_RESERVACION1 { get; set; }
        public virtual TIPO_HABITACION TIPO_HABITACION1 { get; set; }
    }
}
