//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMagnolia.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_BITACORA
    {
        public int ID_TIPO_BITACORA { get; set; }
        public string NOMBRE { get; set; }
    }
}
